demon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('nsqr.urls', namespace="shipment")),
    path('admin/', admin.site.urls),
]

nsqr/urls.py
from django.urls import path
from . import views

app_name = "nsqr"

urlpatterns = [
    path("", views.ResultView.as_view(), name="result-view"),
    path("add", views.TaskCreate.as_view(), name="task-create"),
    path("contact", views.contact, name="contact")
]

nsqr/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    address = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)
    task_status = models.SmallIntegerField(choices=[(1, 'NOT_STARTED'), (2, 'PENDING'), (3, 'FINISHED')], default=1)

    def __str__(self):
        return f"{self.address} - {self.timestamp}"


class Result(models.Model):
    address = models.CharField(max_length=255)
    words_count = models.IntegerField()
    http_status = models.SmallIntegerField()
    task = models.ForeignKey(Task, on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=255, null=True)

    def __str__(self):
        return f"{self.address} - {self.words_count}"

nsqr/forms.py
from django import forms
from nsqr.models import *


class AddPostForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ("address",)

    def __init__(self, *args, **kwargs):
        super(AddPostForm, self).__init__(*args, **kwargs)
        self.fields['address'].widget.attrs.update({'class': 'form-control'})

nsqr/views.py
import threading
import time
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from nsqr.forms import AddPostForm
from nsqr.models import Result, Task
from .tasks import findpy
from celery.result import AsyncResult
# Create your views here.


class Threading(threading.Thread):
    def __init__(self, postdate, let, ids, task):
        self.postdate = postdate
        self.let = let
        self.ids = ids
        self.task = task
        self.status = findpy.AsyncResult(self.ids)
        threading.Thread.__init__(self)

    def run(self):
        Task.objects.filter(id=self.task).update(task_status=2)
        time.sleep(self.postdate)
        Task.objects.filter(id=self.task).update(task_status=3)
        self.let.update(status=self.status.status)
        print(self.status)


class ResultView(ListView):
    model = Result
    template_name = "nsqr/index.html"
    context_object_name = "results"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = Task.objects.all()
        context['nbar'] = 'home'
        return context


class TaskCreate(CreateView):
    model = Task
    template_name = "nsqr/add.html"
    form_class = AddPostForm
    success_url = reverse_lazy("nsqr:result-view")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nbar'] = 'hole'
        return context


def contact(request):
    if request.method == 'POST':
        form = AddPostForm(request.POST)
        if form.is_valid():
            address = form.cleaned_data['address']
            task = form.save()
            x = findpy.delay(address)
            count = findpy(address)
            result = Result(
                address=address,
                words_count=count,
                http_status=200,
                task=task,
                status='STARTED'
            )
            result.save()
            let = Result.objects.filter(id=result.id)
            Threading(10, let, x.task_id, task.id).start()
        else:
            form = AddPostForm(prefix='tasks')
        return redirect('nsqr:result-view')

nsqr/templates/nsqr/add.html
{% extends "nsqr/base.html" %}

{% block content %}

<div class="container-fluid" >
    <h1>Adding a Task</h1>

    <form action="{% url "nsqr:contact" %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}


        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
</div>

{% endblock %}

nsqr/templates/nsqr/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Tasks</title>
</head>
<body>
    <header class="container-fluid">
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link {% if nbar == 'home' %}active{% endif %}" aria-current="page" href="{% url "nsqr:result-view" %}">Resulting list</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if nbar == 'hole' %}active{% endif %}" aria-current="page" href="{% url "nsqr:task-create" %}">Adding tasks</a>
          </li>
        </ul>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer class="container-fluid" style="position: absolute; bottom: 0;">
        <p>&copy; 2021 Partial or complete copying of information from this site for distribution on other resources, including paper, is strictly prohibited.</p>
    </footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

nsqr/templates/nsqr/index.html
{% extends "nsqr/base.html" %}

{% block content %}
    <div class = "container-fluid form-control" style="display: flex; flex-direction: row">
        <div class="container-fluid" style="justify-content: center">
            <h2>Queue:</h2>
            {% for task in tasks %}
                <div>
                    <hr>
                    <p>Address: {{ task.address }}</p>
                    <p>Status: {{ task.get_task_status_display }}</p>
                    <p>Time: {{ task.timestamp }}</p>
                </div>
            {% endfor %}
        </div>
        <div class="container-fluid" style="justify-content: end">
            <h2>Results:</h2>
            {% for result in results %}
                <div>
                    <hr>
                    <p>Address: {{ result.address }}</p>
                    <p>Words count: {{ result.words_count }}</p>
                    <p>Status: {{ result.status }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}